/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

import glb from "./df.glb";

type GLTFResult = GLTF & {
  nodes: {
    df: THREE.Mesh;
  };
  materials: {};
};

export const DF = React.forwardRef<THREE.Group, JSX.IntrinsicElements["group"]>(
  ({ children, ...props }, ref) => {
    const { nodes } = useGLTF(glb) as unknown as GLTFResult;
    return (
      <group ref={ref} {...props} scale={0.1} dispose={null}>
        <group name="dice">
          <mesh name="df" castShadow receiveShadow geometry={nodes.df.geometry}>
            {children}
            <group
              name="0f1_locator_0"
              position={[0, 0, -0.8]}
            />
            <group
              name="00f_locator_-2"
              position={[-0.8, 0, 0]}
            />
            <group
              name="00f_locator_-1"
              position={[0, -0.8, 0]}
            />
            <group
              name="00f_locator_0"
              position={[0, 0, 0.8]}
            />
            <group
              name="00f_locator_2"
              position={[0.8, 0, 0]}
            />
            <group 
              name="00f_locator_1" 
              position={[0, 0.8, 0]} 
            />
          </mesh>
        </group>
      </group>
    );
  }
);

useGLTF.preload(glb);
