/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

import glb from "./d10.glb";

type GLTFResult = GLTF & {
  nodes: {
    d10: THREE.Mesh;
  };
  materials: {};
};

export const D10 = React.forwardRef<
  THREE.Group,
  JSX.IntrinsicElements["group"]
>(({ children, ...props }, ref) => {
  const { nodes } = useGLTF(glb) as unknown as GLTFResult;
  return (
    <group ref={ref} {...props} scale={0.1} dispose={null}>
      <group name="dice">
        <mesh name="d10" castShadow receiveShadow geometry={nodes.d10.geometry}>
          {children}
          <group
            name="010_locator_0"
            position={[0, -0.37, -0.73]}
          />
          <group
            name="010_locator_1"
            position={[-0.0, 0.5, 0.6]}
          />
          <group
            name="010_locator_2"
            position={[0.7, -0.5, -0.1]}
          />
          <group
            name="010_locator_3"
            position={[-0.3, 0.3, -0.7]}
          />
          <group
            name="010_locator_4"
            position={[-0.42, -0.37, 0.6]}
          />
          <group
            name="010_locator_5"
            position={[-0.74, -0.37, -0.33]}
          />
          <group
            name="010_locator_6"
            position={[0.66, 0.42, 0.21]}
          />
          <group
            name="010_locator_7"
            position={[0.4, 0.42, -0.56]}
          />
          <group
            name="010_locator_8"
            position={[0.44, -0.37, 0.59]}
          />
          <group
            name="010_locator_9"
            position={[-0.65, 0.42, 0.22]}
          />
        </mesh>
      </group>
    </group>
  );
});

useGLTF.preload(glb);
