/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

import glb from "./d8.glb";

type GLTFResult = GLTF & {
  nodes: {
    d8: THREE.Mesh;
  };
  materials: {};
};

export const D8 = React.forwardRef<THREE.Group, JSX.IntrinsicElements["group"]>(
  ({ children, ...props }, ref) => {
    const { nodes } = useGLTF(glb) as unknown as GLTFResult;
    return (
      <group ref={ref} {...props} scale={0.1} dispose={null}>
        <group name="dice">
          <mesh name="d8" castShadow receiveShadow geometry={nodes.d8.geometry}>
            {children}
            <group
              name="008_locator_1"
              position={[-0.5, 0.5, 0.5]}
            />
            <group
              name="008_locator_2"
              position={[-0.5, -0.5, 0.5]}
            />
            <group
              name="008_locator_3"
              position={[-0.5, 0.5, -0.5]}
            />
            <group
              name="008_locator_4"
              position={[-0.5, -0.5, -0.5]}
            />
            <group
              name="008_locator_5"
              position={[0.5, 0.5, 0.5]}
            />
            <group
              name="008_locator_6"
              position={[0.5, -0.5, 0.5]}
            />
            <group
              name="008_locator_7"
              position={[0.5, 0.5, -0.5]}
            />
            <group
              name="008_locator_8"
              position={[0.5, -0.5, -0.5]}
            />
          </mesh>
        </group>
      </group>
    );
  }
);

useGLTF.preload(glb);
