/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

import glb from "./df.glb";

type GLTFResult = GLTF & {
  nodes: {
    df: THREE.Mesh;
  };
  materials: {};
};

export const DF = React.forwardRef<THREE.Group, JSX.IntrinsicElements["group"]>(
  ({ children, ...props }, ref) => {
    const { nodes } = useGLTF(glb) as unknown as GLTFResult;
    console.log("1_Доступные меши:", Object.keys(nodes));
    return (
      <group ref={ref} {...props} scale={0.1} dispose={null}>
        <group name="dice">
          <mesh name="df" castShadow receiveShadow geometry={nodes.df.geometry}>
            {children}
            <group
              name="f_locator_1"
              position={[0, -0.77, 0]}
              rotation={[Math.PI, -1.57, 0]}
            />
            <group
              name="f_locator_2"
              position={[-0.77, 0, 0]}
              rotation={[-Math.PI, 0, Math.PI / 2]}
            />
            <group
              name="f_locator_3"
              position={[0, 0, 0.77]}
              rotation={[Math.PI / 2, -1.57, 0]}
            />
            <group
              name="f_locator_4"
              position={[0, 0, -0.77]}
              rotation={[-Math.PI / 2, Math.PI / 2, 0]}
            />
            <group
              name="f_locator_5"
              position={[0.77, 0, 0]}
              rotation={[0, 0, -Math.PI / 2]}
            />
            <group name="f_locator_6" position={[0, 0.77, 0]} />
          </mesh>
        </group>
      </group>
    );
  }
);

useGLTF.preload(glb);
